version: "2.2"
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - type: volume
        source: elk-data
        target: /var/lib/elasticsearch
volumes:
  elk-data:
